# .air.toml
root = "."
tmp_dir = "dist"
[build]
  cmd = "go build -o ./dist/main ."
  bin = "./dist/main"
  delay = 1000 # ms
  exclude_dir = ["assets", "dist", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]